package com.lrcf.yhb.pojo;

import java.io.Serializable;
import java.util.Date;

public class StoreGoods implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.id
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.create_time
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.up_time
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Date upTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.down_time
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Date downTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.all_num
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer allNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.rest_num
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer restNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.order
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.status
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.image3
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String image3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.image2
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String image2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.image
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.url
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.buy_price
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Long buyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.des
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.type
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.sub_type
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer subType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.par_value
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Long parValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.name
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.integral
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Long integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.sale_price
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Long salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.payment
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.productId
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.lifeTime
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer lifetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.durTime
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer durtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.min_invest
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Long minInvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.rate
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Long rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.draw_chance
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer drawChance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.is_draw
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private Integer isDraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.emk1
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String emk1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.emk2
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String emk2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.emk3
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String emk3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.emk4
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String emk4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_goods.emk5
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    private String emk5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.id
     *
     * @return the value of store_goods.id
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.id
     *
     * @param id the value for store_goods.id
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.create_time
     *
     * @return the value of store_goods.create_time
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.create_time
     *
     * @param createTime the value for store_goods.create_time
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.up_time
     *
     * @return the value of store_goods.up_time
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.up_time
     *
     * @param upTime the value for store_goods.up_time
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.down_time
     *
     * @return the value of store_goods.down_time
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Date getDownTime() {
        return downTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.down_time
     *
     * @param downTime the value for store_goods.down_time
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setDownTime(Date downTime) {
        this.downTime = downTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.all_num
     *
     * @return the value of store_goods.all_num
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getAllNum() {
        return allNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.all_num
     *
     * @param allNum the value for store_goods.all_num
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setAllNum(Integer allNum) {
        this.allNum = allNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.rest_num
     *
     * @return the value of store_goods.rest_num
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getRestNum() {
        return restNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.rest_num
     *
     * @param restNum the value for store_goods.rest_num
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setRestNum(Integer restNum) {
        this.restNum = restNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.order
     *
     * @return the value of store_goods.order
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.order
     *
     * @param order the value for store_goods.order
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.status
     *
     * @return the value of store_goods.status
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.status
     *
     * @param status the value for store_goods.status
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.image3
     *
     * @return the value of store_goods.image3
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getImage3() {
        return image3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.image3
     *
     * @param image3 the value for store_goods.image3
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setImage3(String image3) {
        this.image3 = image3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.image2
     *
     * @return the value of store_goods.image2
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getImage2() {
        return image2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.image2
     *
     * @param image2 the value for store_goods.image2
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setImage2(String image2) {
        this.image2 = image2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.image
     *
     * @return the value of store_goods.image
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.image
     *
     * @param image the value for store_goods.image
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.url
     *
     * @return the value of store_goods.url
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.url
     *
     * @param url the value for store_goods.url
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.buy_price
     *
     * @return the value of store_goods.buy_price
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Long getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.buy_price
     *
     * @param buyPrice the value for store_goods.buy_price
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setBuyPrice(Long buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.des
     *
     * @return the value of store_goods.des
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.des
     *
     * @param des the value for store_goods.des
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setDes(String des) {
        this.des = des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.type
     *
     * @return the value of store_goods.type
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.type
     *
     * @param type the value for store_goods.type
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.sub_type
     *
     * @return the value of store_goods.sub_type
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.sub_type
     *
     * @param subType the value for store_goods.sub_type
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setSubType(Integer subType) {
        this.subType = subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.par_value
     *
     * @return the value of store_goods.par_value
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Long getParValue() {
        return parValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.par_value
     *
     * @param parValue the value for store_goods.par_value
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setParValue(Long parValue) {
        this.parValue = parValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.name
     *
     * @return the value of store_goods.name
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.name
     *
     * @param name the value for store_goods.name
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.integral
     *
     * @return the value of store_goods.integral
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Long getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.integral
     *
     * @param integral the value for store_goods.integral
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setIntegral(Long integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.sale_price
     *
     * @return the value of store_goods.sale_price
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.sale_price
     *
     * @param salePrice the value for store_goods.sale_price
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.payment
     *
     * @return the value of store_goods.payment
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.payment
     *
     * @param payment the value for store_goods.payment
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setPayment(Integer payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.productId
     *
     * @return the value of store_goods.productId
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.productId
     *
     * @param productid the value for store_goods.productId
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.lifeTime
     *
     * @return the value of store_goods.lifeTime
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getLifetime() {
        return lifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.lifeTime
     *
     * @param lifetime the value for store_goods.lifeTime
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setLifetime(Integer lifetime) {
        this.lifetime = lifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.durTime
     *
     * @return the value of store_goods.durTime
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getDurtime() {
        return durtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.durTime
     *
     * @param durtime the value for store_goods.durTime
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setDurtime(Integer durtime) {
        this.durtime = durtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.min_invest
     *
     * @return the value of store_goods.min_invest
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Long getMinInvest() {
        return minInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.min_invest
     *
     * @param minInvest the value for store_goods.min_invest
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setMinInvest(Long minInvest) {
        this.minInvest = minInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.rate
     *
     * @return the value of store_goods.rate
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Long getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.rate
     *
     * @param rate the value for store_goods.rate
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setRate(Long rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.draw_chance
     *
     * @return the value of store_goods.draw_chance
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getDrawChance() {
        return drawChance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.draw_chance
     *
     * @param drawChance the value for store_goods.draw_chance
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setDrawChance(Integer drawChance) {
        this.drawChance = drawChance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.is_draw
     *
     * @return the value of store_goods.is_draw
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public Integer getIsDraw() {
        return isDraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.is_draw
     *
     * @param isDraw the value for store_goods.is_draw
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setIsDraw(Integer isDraw) {
        this.isDraw = isDraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.emk1
     *
     * @return the value of store_goods.emk1
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getEmk1() {
        return emk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.emk1
     *
     * @param emk1 the value for store_goods.emk1
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setEmk1(String emk1) {
        this.emk1 = emk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.emk2
     *
     * @return the value of store_goods.emk2
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getEmk2() {
        return emk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.emk2
     *
     * @param emk2 the value for store_goods.emk2
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setEmk2(String emk2) {
        this.emk2 = emk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.emk3
     *
     * @return the value of store_goods.emk3
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getEmk3() {
        return emk3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.emk3
     *
     * @param emk3 the value for store_goods.emk3
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setEmk3(String emk3) {
        this.emk3 = emk3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.emk4
     *
     * @return the value of store_goods.emk4
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getEmk4() {
        return emk4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.emk4
     *
     * @param emk4 the value for store_goods.emk4
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setEmk4(String emk4) {
        this.emk4 = emk4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_goods.emk5
     *
     * @return the value of store_goods.emk5
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public String getEmk5() {
        return emk5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_goods.emk5
     *
     * @param emk5 the value for store_goods.emk5
     *
     * @mbggenerated Tue Jun 13 14:17:09 GMT+08:00 2017
     */
    public void setEmk5(String emk5) {
        this.emk5 = emk5;
    }
}