package com.lrcf.yhb.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class AccountsUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.UserID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.UserName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.UserPassword
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.CheckPassword
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String checkpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.TrueName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.CardID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.CompanyName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.CompanyAddress
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String companyaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.Activity
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Boolean activity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.ParentID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.IsAgent
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Boolean isagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.LineCount
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Integer linecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.IsAuditUser
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Boolean isaudituser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.Style
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Integer style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.UserLevel
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Integer userlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.PayName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String payname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.PayBank
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String paybank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.PayBankAddress
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String paybankaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.PayBankCardNumber
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String paybankcardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.UserQuestion
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String userquestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.UserAnswer
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String useranswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.QQ
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.Telphone
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.Email
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.CreateTime
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.PlatID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String platid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.OpenMoney
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private BigDecimal openmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.PayFeeUserIn
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private BigDecimal payfeeuserin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.MaxMoney
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private BigDecimal maxmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.RptEmail
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String rptemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.IdntfCode
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Integer idntfcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.IdntfCodeCrTime
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Date idntfcodecrtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.YBalance
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private BigDecimal ybalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.IsMember
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Boolean ismember;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.Ips_Id
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String ipsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.Ips_usrCustId
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String ipsUsrcustid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.DeviceToken
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String devicetoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.extractCount
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private Integer extractcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.benefitGetFreeTime
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String benefitgetfreetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.Logo
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private byte[] logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.HeadImg
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private byte[] headimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.User_ek1
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String userEk1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.User_ek2
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String userEk2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_users.User_ek3
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    private String userEk3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.UserID
     *
     * @return the value of accounts_users.UserID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.UserID
     *
     * @param userid the value for accounts_users.UserID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.UserName
     *
     * @return the value of accounts_users.UserName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.UserName
     *
     * @param username the value for accounts_users.UserName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.UserPassword
     *
     * @return the value of accounts_users.UserPassword
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.UserPassword
     *
     * @param userpassword the value for accounts_users.UserPassword
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.CheckPassword
     *
     * @return the value of accounts_users.CheckPassword
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getCheckpassword() {
        return checkpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.CheckPassword
     *
     * @param checkpassword the value for accounts_users.CheckPassword
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setCheckpassword(String checkpassword) {
        this.checkpassword = checkpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.TrueName
     *
     * @return the value of accounts_users.TrueName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.TrueName
     *
     * @param truename the value for accounts_users.TrueName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.CardID
     *
     * @return the value of accounts_users.CardID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.CardID
     *
     * @param cardid the value for accounts_users.CardID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.CompanyName
     *
     * @return the value of accounts_users.CompanyName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.CompanyName
     *
     * @param companyname the value for accounts_users.CompanyName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.CompanyAddress
     *
     * @return the value of accounts_users.CompanyAddress
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getCompanyaddress() {
        return companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.CompanyAddress
     *
     * @param companyaddress the value for accounts_users.CompanyAddress
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setCompanyaddress(String companyaddress) {
        this.companyaddress = companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.Activity
     *
     * @return the value of accounts_users.Activity
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Boolean getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.Activity
     *
     * @param activity the value for accounts_users.Activity
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.ParentID
     *
     * @return the value of accounts_users.ParentID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.ParentID
     *
     * @param parentid the value for accounts_users.ParentID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.IsAgent
     *
     * @return the value of accounts_users.IsAgent
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Boolean getIsagent() {
        return isagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.IsAgent
     *
     * @param isagent the value for accounts_users.IsAgent
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setIsagent(Boolean isagent) {
        this.isagent = isagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.LineCount
     *
     * @return the value of accounts_users.LineCount
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Integer getLinecount() {
        return linecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.LineCount
     *
     * @param linecount the value for accounts_users.LineCount
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setLinecount(Integer linecount) {
        this.linecount = linecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.IsAuditUser
     *
     * @return the value of accounts_users.IsAuditUser
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Boolean getIsaudituser() {
        return isaudituser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.IsAuditUser
     *
     * @param isaudituser the value for accounts_users.IsAuditUser
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setIsaudituser(Boolean isaudituser) {
        this.isaudituser = isaudituser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.Style
     *
     * @return the value of accounts_users.Style
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Integer getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.Style
     *
     * @param style the value for accounts_users.Style
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setStyle(Integer style) {
        this.style = style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.UserLevel
     *
     * @return the value of accounts_users.UserLevel
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Integer getUserlevel() {
        return userlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.UserLevel
     *
     * @param userlevel the value for accounts_users.UserLevel
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setUserlevel(Integer userlevel) {
        this.userlevel = userlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.PayName
     *
     * @return the value of accounts_users.PayName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getPayname() {
        return payname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.PayName
     *
     * @param payname the value for accounts_users.PayName
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setPayname(String payname) {
        this.payname = payname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.PayBank
     *
     * @return the value of accounts_users.PayBank
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getPaybank() {
        return paybank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.PayBank
     *
     * @param paybank the value for accounts_users.PayBank
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setPaybank(String paybank) {
        this.paybank = paybank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.PayBankAddress
     *
     * @return the value of accounts_users.PayBankAddress
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getPaybankaddress() {
        return paybankaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.PayBankAddress
     *
     * @param paybankaddress the value for accounts_users.PayBankAddress
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setPaybankaddress(String paybankaddress) {
        this.paybankaddress = paybankaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.PayBankCardNumber
     *
     * @return the value of accounts_users.PayBankCardNumber
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getPaybankcardnumber() {
        return paybankcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.PayBankCardNumber
     *
     * @param paybankcardnumber the value for accounts_users.PayBankCardNumber
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setPaybankcardnumber(String paybankcardnumber) {
        this.paybankcardnumber = paybankcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.UserQuestion
     *
     * @return the value of accounts_users.UserQuestion
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getUserquestion() {
        return userquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.UserQuestion
     *
     * @param userquestion the value for accounts_users.UserQuestion
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setUserquestion(String userquestion) {
        this.userquestion = userquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.UserAnswer
     *
     * @return the value of accounts_users.UserAnswer
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getUseranswer() {
        return useranswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.UserAnswer
     *
     * @param useranswer the value for accounts_users.UserAnswer
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setUseranswer(String useranswer) {
        this.useranswer = useranswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.QQ
     *
     * @return the value of accounts_users.QQ
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.QQ
     *
     * @param qq the value for accounts_users.QQ
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.Telphone
     *
     * @return the value of accounts_users.Telphone
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.Telphone
     *
     * @param telphone the value for accounts_users.Telphone
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.Email
     *
     * @return the value of accounts_users.Email
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.Email
     *
     * @param email the value for accounts_users.Email
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.CreateTime
     *
     * @return the value of accounts_users.CreateTime
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.CreateTime
     *
     * @param createtime the value for accounts_users.CreateTime
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.PlatID
     *
     * @return the value of accounts_users.PlatID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getPlatid() {
        return platid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.PlatID
     *
     * @param platid the value for accounts_users.PlatID
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setPlatid(String platid) {
        this.platid = platid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.OpenMoney
     *
     * @return the value of accounts_users.OpenMoney
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public BigDecimal getOpenmoney() {
        return openmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.OpenMoney
     *
     * @param openmoney the value for accounts_users.OpenMoney
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setOpenmoney(BigDecimal openmoney) {
        this.openmoney = openmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.PayFeeUserIn
     *
     * @return the value of accounts_users.PayFeeUserIn
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public BigDecimal getPayfeeuserin() {
        return payfeeuserin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.PayFeeUserIn
     *
     * @param payfeeuserin the value for accounts_users.PayFeeUserIn
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setPayfeeuserin(BigDecimal payfeeuserin) {
        this.payfeeuserin = payfeeuserin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.MaxMoney
     *
     * @return the value of accounts_users.MaxMoney
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public BigDecimal getMaxmoney() {
        return maxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.MaxMoney
     *
     * @param maxmoney the value for accounts_users.MaxMoney
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setMaxmoney(BigDecimal maxmoney) {
        this.maxmoney = maxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.RptEmail
     *
     * @return the value of accounts_users.RptEmail
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getRptemail() {
        return rptemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.RptEmail
     *
     * @param rptemail the value for accounts_users.RptEmail
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setRptemail(String rptemail) {
        this.rptemail = rptemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.IdntfCode
     *
     * @return the value of accounts_users.IdntfCode
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Integer getIdntfcode() {
        return idntfcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.IdntfCode
     *
     * @param idntfcode the value for accounts_users.IdntfCode
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setIdntfcode(Integer idntfcode) {
        this.idntfcode = idntfcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.IdntfCodeCrTime
     *
     * @return the value of accounts_users.IdntfCodeCrTime
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Date getIdntfcodecrtime() {
        return idntfcodecrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.IdntfCodeCrTime
     *
     * @param idntfcodecrtime the value for accounts_users.IdntfCodeCrTime
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setIdntfcodecrtime(Date idntfcodecrtime) {
        this.idntfcodecrtime = idntfcodecrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.YBalance
     *
     * @return the value of accounts_users.YBalance
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public BigDecimal getYbalance() {
        return ybalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.YBalance
     *
     * @param ybalance the value for accounts_users.YBalance
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setYbalance(BigDecimal ybalance) {
        this.ybalance = ybalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.IsMember
     *
     * @return the value of accounts_users.IsMember
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Boolean getIsmember() {
        return ismember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.IsMember
     *
     * @param ismember the value for accounts_users.IsMember
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setIsmember(Boolean ismember) {
        this.ismember = ismember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.Ips_Id
     *
     * @return the value of accounts_users.Ips_Id
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getIpsId() {
        return ipsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.Ips_Id
     *
     * @param ipsId the value for accounts_users.Ips_Id
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setIpsId(String ipsId) {
        this.ipsId = ipsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.Ips_usrCustId
     *
     * @return the value of accounts_users.Ips_usrCustId
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getIpsUsrcustid() {
        return ipsUsrcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.Ips_usrCustId
     *
     * @param ipsUsrcustid the value for accounts_users.Ips_usrCustId
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setIpsUsrcustid(String ipsUsrcustid) {
        this.ipsUsrcustid = ipsUsrcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.DeviceToken
     *
     * @return the value of accounts_users.DeviceToken
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getDevicetoken() {
        return devicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.DeviceToken
     *
     * @param devicetoken the value for accounts_users.DeviceToken
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setDevicetoken(String devicetoken) {
        this.devicetoken = devicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.extractCount
     *
     * @return the value of accounts_users.extractCount
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public Integer getExtractcount() {
        return extractcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.extractCount
     *
     * @param extractcount the value for accounts_users.extractCount
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setExtractcount(Integer extractcount) {
        this.extractcount = extractcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.benefitGetFreeTime
     *
     * @return the value of accounts_users.benefitGetFreeTime
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getBenefitgetfreetime() {
        return benefitgetfreetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.benefitGetFreeTime
     *
     * @param benefitgetfreetime the value for accounts_users.benefitGetFreeTime
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setBenefitgetfreetime(String benefitgetfreetime) {
        this.benefitgetfreetime = benefitgetfreetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.Logo
     *
     * @return the value of accounts_users.Logo
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public byte[] getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.Logo
     *
     * @param logo the value for accounts_users.Logo
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.HeadImg
     *
     * @return the value of accounts_users.HeadImg
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public byte[] getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.HeadImg
     *
     * @param headimg the value for accounts_users.HeadImg
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setHeadimg(byte[] headimg) {
        this.headimg = headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.User_ek1
     *
     * @return the value of accounts_users.User_ek1
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getUserEk1() {
        return userEk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.User_ek1
     *
     * @param userEk1 the value for accounts_users.User_ek1
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setUserEk1(String userEk1) {
        this.userEk1 = userEk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.User_ek2
     *
     * @return the value of accounts_users.User_ek2
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getUserEk2() {
        return userEk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.User_ek2
     *
     * @param userEk2 the value for accounts_users.User_ek2
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setUserEk2(String userEk2) {
        this.userEk2 = userEk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_users.User_ek3
     *
     * @return the value of accounts_users.User_ek3
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public String getUserEk3() {
        return userEk3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_users.User_ek3
     *
     * @param userEk3 the value for accounts_users.User_ek3
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    public void setUserEk3(String userEk3) {
        this.userEk3 = userEk3;
    }
}