package com.lrcf.yhb.dao.mapper;

import com.lrcf.yhb.pojo.AccountsUsers;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AccountsUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_users
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_users
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    int insert(AccountsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_users
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    AccountsUsers selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_users
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    List<AccountsUsers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_users
     *
     * @mbggenerated Tue Jun 13 14:19:15 GMT+08:00 2017
     */
    int updateByPrimaryKey(AccountsUsers record);
}